### ISSUE TITLE
Initial testing

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thedaily#1]
Here are a few things to watch for when testing:
- **Test with use cases centered on art historians** - If you need some extra guidance, here are some responses from a survey of art historians: https://docs.google.com/a/kimisgold.com/forms/d/12xtke5HPaMa58iIUhLCGMaNjKlFgT8YKqqL5CkzCIS0/viewanalytics. If you see any ideas from the survey that could be incorporated in the theme, I welcome feature requests.
- **Cross-browser functionality** - I'm using a lot of flexbox for layout in this theme, so it's especially important to check that everything works on IE and Firefox.

For bugs you find, please submit individual issues and link back to this one. (Just include "#1" in the body of your issue.)

**Comment by alyssafahringer** [comment]
When viewing a collection page on the public side, is the title supposed to not be left-justified? 
![screen shot 2016-08-08 at 2 34 54 pm](https://cloud.githubusercontent.com/assets/8807816/17491393/70fb7c02-5d75-11e6-87bb-8935be21dcde.png)

**Comment by alyssafahringer** [comment]
For exhibits with gallery blocks, there seems to be some extra space in the bottom bar: 
![screen shot 2016-08-08 at 2 50 59 pm](https://cloud.githubusercontent.com/assets/8807816/17491997/edb8aeb6-5d77-11e6-954b-2508433cd258.png) 
![screen shot 2016-08-08 at 2 54 10 pm](https://cloud.githubusercontent.com/assets/8807816/17492013/0077816c-5d78-11e6-9c08-17ff16b628be.png)

**Comment by kimisgold** [comment]
> When viewing a collection page on the public side, is the title supposed to not be left-justified? 

Yes. It looks less weird when you have more than one metadata field populated.

> For exhibits with gallery blocks, there seems to be some extra space in the bottom bar: 

It's a little difficult for me to understand the question based on the screenshots. Do you have a URL?

**Comment by alyssafahringer** [comment]
Sorry about that - http://dev.omeka.org/mebrett/Omeka/exhibits/show/whymall/whymall & http://dev.omeka.org/afahring/omeka/exhibits/show/all-my-stuff/things
