### ISSUE TITLE
Test new lightgallery viewer

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thedaily#14]
See https://github.com/omeka/theme-bigpicture/issues/20. This should also cover #12 and #13.

**Comment by mebrett** [comment]
In TheDaily and CenterRow (but not big picture) very tall images are throwing off the lightviewer - ex http://dev.omeka.org/mebrett/Omeka/items/show/2553

**Comment by kimisgold** [comment]
I think it's a bottom padding style from the gallery plugins. I've included an override in both themes that should be ready to look at.

**Comment by mebrett** [comment]
That fixed it!
