### ISSUE TITLE
Test that non-image files respect to "link to file metadata" setting

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thedaily#15]
The Daily groups files that can't display in the image viewer in a "Files" section in the metadata. On the master branch, test that these file links go to either the metadata view or the original file based off the "link to file metadata" appearance setting.

**Comment by mebrett** [comment]
It's going to the metadata view (files/show) regardless of whether the "Link to File Metadata" box is checked, for files which are txt or pdf at least.

**Comment by kimisgold** [comment]
The correction is ready to pull and test.

**Comment by mebrett** [comment]
Correction succesful.
