### ISSUE TITLE
Testing: Video support in item/show galleries

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thedaily#18]
This feature has already been included in the latest release, but I wanted to get more eyes on it before it gets pulled into Omeka.net. Please test the following:

* Videos attached to items appear in the gallery and can play both as the only files and as part of a mixed set of file types.
* Subtitle files can be attached and work properly.
  * They should not appear in the "Other Files" listing.
  * Track and video files must all share the same base file name (ex: "video.mp4", "video.vtt")
  * Theme now supports the following values for track metadata:
        * Dublin Core: Type ("subtitles", "captions", etc)
        * Dublin Core: Language (the language code for the track)
        * Dublin Core: Title (the label for the track)
  * Multiple language tracks are supported. They still must share the same base file name as the video: the user differentiates between them using their Dublin Core metadata.

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by dth1692** [comment]
The metadata is missing on Edge and Chrome.  This is what I get and here is the [corresponding page on Histories of the National Mall.](http://mallhistory.org/items/show/542)

![the daily metadata](https://user-images.githubusercontent.com/35391752/122327310-a7aa4880-cefb-11eb-868b-d01a5363d1c2.JPG)

**Comment by kimisgold** [comment]
@dth1692 Thanks for that catch. The fix should be pushed to staging and ready for another look.

**Comment by katknow** [comment]
The metadata is now appearing, but the little broken thumbnail is still there (but it's not on Big Picture theme, if that comparison is relevant). Same as with the Big Picture theme, the video plays perfectly fine, and subtitles do not appear as other files. However, the English subtitles only play if I’m logged in on Firefox, Chrome, and Edge and the options do not show for French and Spanish at all until you navigate to the public page while logged in. All subtitle options do appear in menu on video on public page even though they do not work if not logged in. Tried clearing cache but still didn’t work to fix. All of the subtitles do work when using Safari. I've attached screenshots--it wouldn't let me drop them in here for some reason.
[The Daily Theme Screenshots.docx](https://github.com/omeka/theme-thedaily/files/6672897/The.Daily.Theme.Screenshots.docx)

**Comment by kimisgold** [comment]
@katknow @dth1692 I realize I forgot to follow up and say the fix has been pushed to staging for the three affected themes. Could you two pull and test this again?

**Comment by katknow** [comment]
@kimisgold  this seems to be working on the front end across Chrome, Safari, Firefox, and Edge now. English is still the only option on the back end, but I don't know how much that matters. Also, this theme still has the broken thumbnail showing up below the video: https://katknowtesting.omeka-staging.net/items/show/491

**Comment by kimisgold** [comment]
The broken thumbnail should now be fixed, though I've also made changes that may not make it immediately obvious. Now, if an item only has a single visual media attached, it will **not** show the thumbnail navigation. To make sure the thumbnails work, attach another image or video to the item.

**Comment by katknow** [comment]
@kimisgold that seemed to do it! 
![image](https://user-images.githubusercontent.com/84726696/124045567-ecdf7780-d9dd-11eb-83f4-44bfed4bf270.png)
