### ISSUE TITLE
Exhibit top of page navigation displaying oddly

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-thedaily#2]
Ref #1 

The exhibit navigation displaying across the top of the page is displaying pages (particularly nested pages) in a disorderly fashion. Exhibit subpage titles run together - the end of one butts right into the start of the next creating a single visual "word". 

Here is the exhibit page hierarchy: 
![screen shot 2016-08-03 at 4 16 09 pm](https://cloud.githubusercontent.com/assets/2314070/17381332/649e235e-5999-11e6-923d-5c4edce78c6c.png)

And here is how it's displaying at http://dev.omeka.org/mebrett/Omeka/exhibits/show/mall-stuff: 
![screen shot 2016-08-03 at 4 42 12 pm](https://cloud.githubusercontent.com/assets/2314070/17381344/7088b3f0-5999-11e6-9fce-b08b05300369.png)

Shown in Chrome but issue persists in Firefox and Safari

**Comment by kimisgold** [comment]
There are a number of issues with the exhibit navigation in its current state, so based on testing and working group feedback, I've redesigned it in the `exhibit-side-nav` branch. @mebrett, would you mind taking a look at it?

**Comment by mebrett** [comment]
Everything works fine, even with 3 levels of exhibit pages. I like the way the menu follows as you scroll, so that you can easily get to the next section/page at the bottom of a long piece of content.

**Comment by kimisgold** [comment]
@mebrett Nice! I also think that having that navigation on hand at all times makes the previous/next page navigation less useful on desktop, though still necessary on mobile where the navigation doesn't follow the scroll. How does that sound to you?

**Comment by mebrett** [comment]
I agree - I just looked on the phone and right now there's a Back to the Top button at the end of the page which I quite liked. Because it popped me right back to the exhibit nav I was able not just to move forward but go anywhere in the exhibit easily.
