### ISSUE TITLE
Inline Navigation Bar on Desktop

### ISSUE THREAD

**Issue by sethwilsonUS** [omeka/theme-thedaily#9]
Hello,

I'm trying to make the navigation links appear inline on the menubar on desktop, rather than using the hamburger. I'm not a CSS expert and I'm having a little trouble. Can you help at least get me on the right track with some styles or general guidance?

Thank you!

**Comment by kimisgold** [comment]
Hello, sorry for the delayed response. My recommendation would be to start with overriding the theme's styles using [CSS Editor](https://omeka.org/classic/plugins/CSSEditor/) and enter the following block: 

```
/* This hides the menu toggle. */

#top-nav .menu-toggle {
  display: none;
}

/ * This places the search toggle after the menu. */

#search-container {
  order: 2;
}

/* 
  The following block changes the menu 
  from a full screen display to inline blocks in the header. 
*/

#top-nav > ul {
  position: static;
  top: auto;
  left: auto;
  right: auto;
  background-color: transparent;
  height: auto;
  display: inline-block;
  padding: 0;
}

#top-nav > ul > li {
  display: inline-block;
  padding: 0;
  width: auto;
  margin: 0 1em;
}
```

I hope this is a helpful start!
